### ISSUE TITLE
loaddata cmd not working getting error -> sqlite3.OperationalError: no such table: oidc_provider_client__old

### ISSUE THREAD

**Issue by IshwarChincholkar** [johnpaulett/sham-oidc#9]
Python version 3.8.10
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0

Steps to reproduce :
1) docker-compose run oidc ./manage.py loaddata /tmp/accounts_fixture.json

error message :
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 326, in execute
    return Database.Cursor.execute(self, query)
sqlite3.OperationalError: no such table: oidc_provider_client__old

```

**Comment by johnpaulett** [comment]
Looks like the standard Django error when the database has not been set up via `manage.py migrate`. 

If you are using the git checkout of sham-oidc, have you run the `migrate` (and other commands) per https://github.com/johnpaulett/sham-oidc#container-setup?

**Comment by johnpaulett** [comment]
You mentioned Python 3.8.  That is not what the [Dockerfile is using](https://github.com/johnpaulett/sham-oidc/blob/master/Dockerfile#L1) which would be the Python version that the `./manage.py loaddata` would be using.

Adding to my prior comment, I suspect either `migrate` was not run, there was an error in `migrate` and the sqlite DB was not created.  The output of `migrate` would provide answers.

**Comment by IshwarChincholkar** [comment]
Actually Python 3.8 is local python version.
More logs :
```
docker-compose run oidc ./manage.py migrate
```
```
Creating oidc_run ... done
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, oidc_provider, sessions
Running migrations:
  No migrations to apply.
```

```
docker-compose run oidc ./manage.py loaddata /tmp/accounts_fixture.json
```
```
Creating oidc_run ... done
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 326, in execute
    return Database.Cursor.execute(self, query)
sqlite3.OperationalError: no such table: oidc_provider_client__old

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/loaddata.py", line 69, in handle
    self.loaddata(fixture_labels)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/loaddata.py", line 115, in loaddata
    connection.check_constraints(table_names=table_names)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 286, in check_constraints
    column_name, referenced_column_name,
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 326, in execute
    return Database.Cursor.execute(self, query)
django.db.utils.OperationalError: Problem installing fixtures: no such table: oidc_provider_client__old
ERROR: 1
```

**Comment by johnpaulett** [comment]
`oidc_provider_client__old` (the "__old" part is wrong) in your fixtures is not a valid table for [django-oidc-provider](https://github.com/juanifioren/django-oidc-provider).  

You can prove this via:
```
docker-compose run oidc ./manage.py shell -c "from django.db import connection; c=connection.cursor(); print(c.execute('SELECT name FROM sqlite_master WHERE type=\'table\'').fetchall())"
```

The fixtures file is not part of this repository -- so it appears to be a problem on your end with some manual modification to the fixture file (guessing since it is using Django's `loaddata` it came from `dumpdata` and was modified).

**Comment by IshwarChincholkar** [comment]
Unable to find _old table after ran this cmd:
```
 docker-compose run oidc ./manage.py shell -c "from django.db import connection; c=connection.cursor(); print(c.execute('SELECT name FROM sqlite_master WHERE type=\'table\'').fetchall())"
Creating oidc_run ... done

[('django_migrations',), ('sqlite_sequence',), ('auth_group',), ('auth_group_permissions',), ('auth_user_groups',), 
('auth_user_user_permissions',), ('django_admin_log',), ('django_content_type',), ('auth_permission',), ('auth_user',), 
('oidc_provider_rsakey',), ('oidc_provider_code',), ('oidc_provider_userconsent',), ('oidc_provider_token',),
 ('oidc_provider_client',), ('django_session',)]
```
And dumpdata  also looks good , may be something is wrong with  .json file.
